### ISSUE TITLE
More tv shows, parameters and query

### ISSUE THREAD

**Issue by KristofKekesi** [AugustoMarcelo/mcuapi#8]
## More tv shows
 Hi can you add more tv shows please? I'm thinking about the ABC series like Agents of SHIELD, Agent Carter and Inhumans. As far as I know Agents of SHIELD and Agent carter are kinda connected to the MCU.

## Response parameters
Can you change the `directed_by`  parameter to be a list? For the Avangers Endgame it is confusing to have a list with two names instead of a list with two elements.

## Query parameters
Are you tought adding query parameters to the API? It would be really useful for searching by title, phase and saga.

##
Awesome API, will use in the future. Thanks for your work and for making it open source.

**Comment by AugustoMarcelo** [comment]
Hello, @KristofKekesi, how are you? Thanks for the feedback!

### More tv series
I agree that Agent Carter and SHIELD Agents are connected with the MCU. I haven't added them yet because I was waiting for some news or confirmation from boss Kevin Feige. Regarding Inhumans, I think that even the Netflix series are ahead... lol

### Response parameters
I will review this change. For now, you can make a split by the comma.
```js
const directors = movie.directed_by.split(', '); //["Anthony Russo", "Joe Russo"]
```

### Query parameters
Currently, you can do the filter as follows:
```js
https://mcuapi.herokuapp.com/api/v1/movies?filter=phase=3
https://mcuapi.herokuapp.com/api/v1/movies?filter=title=Iron
https://mcuapi.herokuapp.com/api/v1/movies?filter=saga=Infinity
```
I preferred this approach to allow filtering by any column. You can try on the interactive [documentation](https://mcuapi.herokuapp.com/docs/)

Again, thanks for the feedback!

**Comment by KristofKekesi** [comment]
Thanks for your fast reply. Have a great day :D

**Comment by KristofKekesi** [comment]
Hi!

Captain Marvel 2 was renamed to The Marvels. And the Black Panter is Wakanda Forever now.

**Comment by AugustoMarcelo** [comment]
Hi, @KristofKekesi 

I have already adjusted this information in the seed file. I am waiting for the new covers. I download from Marvel's own website, to maintain the standard of covers.
